### ISSUE TITLE
Do i need to upload whole src folder as zip including node modules.? 

### ISSUE THREAD

**Issue by kirangavini** [chriselsen/Alexa_NextMuni#1]
I am just assuming that node modules is required for parse string command. I tried uploading nodemodules as well, but it is not getting uploaded. I couldnt call the test function some how. Can you help me figure it out?

**Comment by chriselsen** [comment]
Yes, the content of the src folder - including the XML node moules - will have to go into the zip file, whereas "index.js" is at the root level. 
Also have a look at https://www.edge-cloud.net/2016/10/10/amazon-alexa-skill-san-francisco-muni/

**Comment by kirangavini** [comment]
Thanks for your response. When i was zipping the src folder, it made a copy of itself inside. I went in and zip all files together. It works great. :)
